apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-infra
  namespace: argocd  # The Application resource itself lives in argocd namespace
spec:
  project: default
  source:
    repoURL: https://github.com/TFWulp-Levarne/ArgoCD-example-project.git
    targetRevision: HEAD
    path: infrastructure/kafka  # <--- Points to your new unrelated folder
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka            # <--- Deploys the actual Kafka pods here
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true    # <--- Creates the 'kafka' namespace automatically